<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('operadorCheckinheader');
$ticket = Data::get('ticket');
$users = Data::get('users');
$flights = Data::get('flights');
ErrMgr::attach($ticket) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Alterar informações do checkin do bilhete <?=$ticket->id?> do passageiro <?=$ticket->idutilizador?></h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('ticket/update', $ticket->id)?>">
                        <?php if ($ticket->checkin == 0){ ?>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="checkin">Checkin<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$ticket->checkin?>" class="form-control" name="checkin" placeholder="">
                                <?= ErrMgr::bind('checkin') ?>
                            </div>
                        </div>

                        </div>
                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>

                    <?php } else{ ?>
                    <label class="col-lg-4 text-right">Já realizou checkin deste passageiro!</label>
                        <div class="col-lg-4 text-right">
                            <button class="btn btn-action" type="submit">Voltar</button>
                        </div>
                    <?php } ?>

                    </form>
                </div>
            </div>



        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
