<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('operadorCheckinheader') ?>
<?php $ticket = Data::get('ticket') ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Informações do bilhete <?=$ticket->id?> do passageiro <?=$ticket->idutilizador?></h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>

                        <form method="post" action="<?=Url::toRoute('operadorcheckin/index')?>">
                            <div class="top-margin">
                                <label>Preco Final</label>
                                <input readonly="true" type="text" value="<?php echo $ticket->precofinal?>" name="precofinal" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Data e Hora de Compra</label>
                                <input readonly="true" type="text" value="<?=$ticket->datahoracompra?>" name="datahoracompra" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Checkin</label>
                                <input readonly="true" type="text" value="<?=$ticket->checkin?>" name="checkin" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Voo ida</label>
                                <input readonly="true" type="text" value="<?=$ticket->idvooida?>" name="idvooida" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Voo volta</label>
                                <input readonly="true" type="text" value="<?=$ticket->idvoovolta?>" name="idvoovolta" class="form-control">
                            </div>

                            <hr>

                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
