<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>


    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Flight Travel Air</b><br><br>Seja bem vindo!</h1>
                <p class="tagline">Se deseja adquirir já o seu bilhete ou consultar todos os nossos voos por favor registe-se se ainda não tiver uma conta ou faça login para aceder à sua área de cliente!</p>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('login/getlogin')?>">LOGIN/REGISTO</a></p>
            </div>
            <div class="row">
                <br>
                <br>
                <br>
            </div>
        </div>
    </header>
    <!-- /Header -->

<?php Layout::includeLayout('footer')?>