<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('adminheader'); ?>

<!-- Header -->
<header id="head">
    <div class="container">
        <div class="row">
            <h1 class="lead"><b>Flight Travel Air</b><br>Área de administrador</h1>
            <p class="tagline">Gestão de aeoportos e de funcionários.</p>
        </div>
    </div>
</header>
<!-- /Header -->


<?php Layout::includeLayout('footer')?>
