<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('gestorVooheader'); ?>

<!-- Header -->
<header id="head">
    <div class="container">
        <div class="row">
            <h1 class="lead"><b>Flight Travel Air</b><br>Área de gestor de voos</h1>
            <p class="tagline">Gestão de voos, escalas e aviões.<br><br><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('flight/index')?>">Gestão de Voos/Escalas</a></p>
            <p class="tagline"><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('plane/index')?>">Gestão de Aviões</a></p>
        </div>
    </div>
</header>
<!-- /Header -->


<?php Layout::includeLayout('footer')?>

