<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader') ?>
<?php $plane = Data::get('plane')?>
<?php ErrMgr::attach($plane) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Registar Novo Avião</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('plane/store')?>">
                            <div class="top-margin">
                                <label>Referência<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$plane->referencia?>" name="referencia" class="form-control" placeholder="Introduza a referencia do aviao">
                                <?= ErrMgr::bind('referencia') ?>
                            </div>

                            <div class="top-margin">
                                <label>Lotação<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$plane->lotacao?>" name="lotacao" class="form-control" placeholder="Introduza a lotacao do aviao">
                                <?= ErrMgr::bind('lotacao') ?>
                            </div>
                            <div class="top-margin">
                                <label>Tipo de avião<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$plane->tipoaviao?>" name="tipoaviao" class="form-control" placeholder="Introduza o tipo de aviao">
                                <?= ErrMgr::bind('tipoaviao') ?>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Registar</button>
                            </div>
                    </div>
                    </form>
                </div>
                <form method="post" action="<?=URL::toRoute('plane/index')?>">
                    <button class="btn btn-danger" type="submit">Cancelar</button>
                </form>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
