<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader') ?>
<?php $plane = Data::get('plane') ?>
<?php ErrMgr::attach($plane) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Alterar informações do Avião <?=$plane->referencia?></h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('plane/update', $plane->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="referencia">Referência:</label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$plane->referencia?>" class="form-control" required name="referencia" placeholder="Introduza a referencia do aviao">
                                <?= ErrMgr::bind('referencia') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="lotacao">Lotação:</label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$plane->lotacao?>" class="form-control" name="lotacao" placeholder="Introduza a lotacao do aviao">
                                <?= ErrMgr::bind('lotacao') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="tipoaviao">Tipo de avião:</label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$plane->tipoaviao?>" class="form-control" name="tipoaviao" placeholder="Introduza o tipo de aviao">
                                <?= ErrMgr::bind('tipoaviao') ?>
                            </div>
                        </div>

                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>



        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
