<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader') ?>
<?php $planes = Data::get('plane') ?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('gestorvoo/index')?>">Home</a></li>
        <li class="active">Aviões</li>
    </ol>

    <h2 class="text-left top-space">Lista de Aviões</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>Referência</h3></th><th><h3>Lotação</h3><th><h3>Tipo de Avião</h3></th><th><h3>Ações de Gestão</h3></th></thead>
                <tbody>
                <?php foreach ($planes as $plane) { ?>
                    <tr>
                        <td><?=$plane->referencia?></td>
                        <td><?=$plane->lotacao?></td>
                        <td><?=$plane->tipoaviao?></td>
                        <td>
                            <a href="<?=Url::toRoute('plane/show', $plane->id)?>" class="btn btn-info" role="button">Ver detalhes</a>
                            <a href="<?=Url::toRoute('plane/edit', $plane->id)?>" class="btn btn-warning" role="button">Editar</a>
                            <a href="<?=Url::toRoute('plane/destroy', $plane->id)?>" class="btn btn-danger" role="button">Eliminar</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>
        <div class="col-sm-6">
            <h3>Registar Novo Avião</h3>
            <p>
                <a href="<?=Url::toRoute('plane/create')?>" class="btn btn-info" role="button">Novo</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
