<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('gestorVooheader') ?>
<?php $plane = Data::get('plane') ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Informações do avião <?=$plane->referencia?></h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>

                        <form method="post" action="<?=Url::toRoute('plane/index')?>">
                            <div class="top-margin">
                                <label>Referência<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?php echo $plane->referencia?>" name="referencia" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Lotação<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$plane->lotacao?>" name="lotacao" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Tipo de Avião<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$plane->tipoaviao?>" name="tipoaviao" class="form-control">
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Voltar</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
