<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $funcionario = Data::get('funcionario') ?>
<?php ErrMgr::attach($funcionario) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Alterar informações do <?=$funcionario->role?> <?=$funcionario->nomecompleto?></h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('funcionario/update', $funcionario->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="nomecompleto">Nome Completo:</label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$funcionario->nomecompleto?>" class="form-control" required name="nomecompleto" placeholder="Introuza o seu nome completo">
                                <?= ErrMgr::bind('nomecompleto') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="morada">Morada:</label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$funcionario->morada?>" class="form-control" name="morada" placeholder="Intrduza a sua morada">
                                <?= ErrMgr::bind('morada') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="email">Email:</label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$funcionario->email?>" class="form-control" name="email" placeholder="Introduza o seu email">
                                <?= ErrMgr::bind('email') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="nif">NIF:</label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$funcionario->nif?>" class="form-control" name="nif" placeholder="Introduza o seu nif">
                                <?= ErrMgr::bind('nif') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="telefone">Telefone:</label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$funcionario->telefone?>" class="form-control" name="telefone" placeholder="Introduza o seu numero de telefone">
                                <?= ErrMgr::bind('telefone') ?>
                            </div>
                        </div>
                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>



        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
