<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader') ?>
<?php $flight = Data::get('flight')?>

<?php ErrMgr::attach($flight) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Registar Novo Voo</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('flight/store')?>">
                            <div class="top-margin">
                                <label>Preço de Voo<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$flight->precovoo?>" name="precovoo" class="form-control" placeholder="Introduza o preço de voo">
                                <?= ErrMgr::bind('precovoo') ?>
                            </div>
                            <div class="top-margin">
                                <label>Origem<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$flight->origem?>" name="origem" class="form-control" placeholder="Introduza a origem do voo">
                                <?= ErrMgr::bind('origem') ?>
                            </div>
                            <div class="top-margin">
                                <label>Destino<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$flight->destino?>" name="destino" class="form-control" placeholder="Introduza o destino do voo">
                                <?= ErrMgr::bind('destino') ?>
                            </div>
                            <div class="top-margin">
                                <label>Data de Origem<span class="text-danger">*</span></label>
                                <input type="datetime-local" autocomplete="off" value="<?=$flight->dataorigem?>" name="dataorigem" class="form-control" placeholder="Introduza a data de origem do voo">
                                <?= ErrMgr::bind('dataorigem') ?>
                            </div>
                            <div class="top-margin">
                                <label>Data de Destino<span class="text-danger">*</span></label>
                                <input type="datetime-local" autocomplete="off" value="<?=$flight->datadestino?>" name="datadestino" class="form-control" placeholder="Introduza a data de destino do voo">
                                <?= ErrMgr::bind('datadestino') ?>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Registar</button>
                            </div>
                    </div>
                    </form>
                </div>
                <form method="post" action="<?=URL::toRoute('flight/index')?>">
                    <button class="btn btn-danger" type="submit">Cancelar</button>
                </form>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
