<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $flight = Data::get('flight')?>
<?php ErrMgr::attach($flight) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Registar Novo Voo</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('flight/store')?>">
                            <div class="top-margin">
                                <label>Preço de Voo<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$flight->precovoo?>" name="precovoo" class="form-control" placeholder="Introduza o preço de voo">
                                <?= ErrMgr::bind('precovoo') ?>
                            </div>
                            <div class="top-margin">
                                <label>Aeroporto associado<span class="text-danger">*</span></label>
                                <select name="idaeroporto" class="form-control" value="<?=$flight->idaeroporto?>">
                                    <option value="<?=Aeroport::find()->where(['id' => $flight->idaeroporto]) ?>">teste</option>
                                </select>
                                <?= ErrMgr::bind('idaeroporto') ?>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Criar</button>
                            </div>
                    </div>
                    </form>
                </div>
                <form method="post" action="<?=URL::toRoute('flight/index')?>">
                    <button class="btn btn-danger" type="submit">Cancelar</button>
                </form>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
