<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader') ?>
<?php $flight = Data::get('flight')?>
<?php ErrMgr::attach($flight) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Alterar informações do Voo <?=$flight->id?></h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('flight/update', $flight->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="precovoo">Preço de Voo<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$flight->precovoo?>" class="form-control" required name="precovoo" placeholder="Introduza o preco do voo">
                                <?= ErrMgr::bind('precovoo') ?>
                            </div>
                        </div>

                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>



        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
