<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader');
$flights = Data::get('flight');
$erro = Data::get('erro');
?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('gestorvoo/index')?>">Home</a></li>
        <li class="active">Voos</li>
    </ol>

    <h2 class="text-left top-space">Lista de Voos</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>Preço</h3></th><th><h3>Origem</h3></th><th><h3>Destino</h3></th><th><h3>Data de origem</h3></th><th><h3>Data de destino</h3></th><th><h3>Ações de Gestão</h3></th></thead>
                <tbody>
                <?php foreach ($flights as $flight) { ?>
                    <tr>
                        <td><?=$flight->precovoo?> €</td>
                        <td><?=$flight->origem?></td>
                        <td><?=$flight->destino?></td>
                        <td><?=$flight->dataorigem->format('Y-m-d')?></td>
                        <td><?=$flight->datadestino->format('Y-m-d')?></td>
                        <div>
                            <p id="erro"><?php if(!$erro instanceof \ArmoredCore\MagicBlankModel) echo $erro; ?></p>
                        </div>
                        <td>
                            <a href="<?=Url::toRoute('scale/index', $flight->id)?>" class="btn btn-info" role="button">Escalas</a>
                            <a href="<?=Url::toRoute('flight/edit', $flight->id)?>" class="btn btn-warning" role="button">Editar</a>
                            <a href="<?=Url::toRoute('flight/destroy', $flight->id)?>" class="btn btn-danger" role="button">Eliminar</a>
                        </td>
                    </tr>

                <?php } ?>
                </tbody>
            </table>

        </div>

        <div class="col-sm-6">
            <h3>Registar um novo Voo</h3>
            <p>
                <a href="<?=Url::toRoute('flight/create')?>" class="btn btn-info" role="button">Registar</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
