<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('operadorCheckinheader') ?>
<?php $flights = Data::get('flight') ?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('operadorcheckin/index')?>">Home</a></li>
        <li class="active">Voos</li>
    </ol>

    <h2 class="text-left top-space">Detalhes de Voos</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>Preço de Voo</h3></th></th></thead>
                <tbody>
                <?php foreach ($flights as $flight) { ?>
                    <tr>
                        <td><?=$flight->precovoo?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
