<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $aeroport = Data::get('aeroport')?>
<?php ErrMgr::attach($aeroport) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Registar Novo Aeroporto</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('aeroport/store')?>">
                            <div class="top-margin">
                                <label>Nome <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$aeroport->nome?>" name="nome" class="form-control" placeholder="Introduza o nome do aeroporto">
                                <?= ErrMgr::bind('nome') ?>
                            </div>
                            <div class="top-margin">
                                <label>Morada <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$aeroport->morada?>" name="morada" class="form-control" placeholder="Introduza a morada do aeroporto">
                                <?= ErrMgr::bind('morada') ?>
                            </div>
                            <div class="top-margin">
                                <label>NIF <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$aeroport->nif?>" name="nif" class="form-control" placeholder="Introduza o nif do aeroporto">
                                <?= ErrMgr::bind('nif') ?>
                            </div>
                            <div class="top-margin">
                                <label>Telefone <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$aeroport->telefone?>" name="telefone" class="form-control" placeholder="Introduza o telefone do aeroporto">
                                <?= ErrMgr::bind('telefone') ?>
                            </div>
                            <div class="top-margin">
                                <label>Email <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$aeroport->email?>" name="email" class="form-control" placeholder="Introduza o email do aeroporto">
                                <?= ErrMgr::bind('email') ?>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Registar</button>
                            </div>
                    </div>
                    </form>
                </div>
                <form method="post" action="<?=URL::toRoute('aeroport/index')?>">
                    <button class="btn btn-danger" type="submit">Cancelar</button>
                </form>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

