<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $aeroport = Data::get('aeroport') ?>
<?php ErrMgr::attach($aeroport) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Alterar informações do aeroporto <?=$aeroport->nome?></h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('aeroport/update', $aeroport->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="nome">Nome:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$aeroport->nome?>" class="form-control" required name="nome" placeholder="Introduza o nome do aeroporto">
                                <?= ErrMgr::bind('nome') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="morada">Morada:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$aeroport->morada?>" class="form-control" required name="morada" placeholder="Introduza a morada do aeroporto">
                                <?= ErrMgr::bind('morada') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="nif">NIF:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$aeroport->nif?>" class="form-control" required name="nif" placeholder="Introduza o nif do aeroporto">
                                <?= ErrMgr::bind('nif') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="telefone">Telefone:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$aeroport->telefone?>" class="form-control" required name="telefone" placeholder="Introduza o telefone do aeroporto">
                                <?= ErrMgr::bind('telefone') ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="email">Email:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$aeroport->email?>" class="form-control" required name="email" placeholder="Introduza o email do aeroporto">
                                <?= ErrMgr::bind('email') ?>
                            </div>
                        </div>
                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>



        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

