<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('passageiroheader');
$user = Data::get('user');
ErrMgr::attach($user); ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Dados pessoais de <?=$user->nomecompleto?></h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('passageiro/update', $user->id)?>">
                            <div class="top-margin">
                                <label>Nome <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->nomecompleto?>" name="nomecompleto" class="form-control">
                                <?= ErrMgr::bind('nomecompleto') ?>
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" value="<?=$user->password?>" name="password" class="form-control">
                                <?= ErrMgr::bind('password') ?>
                            </div>
                            <div class="top-margin">
                                <label>Email <span class="text-danger">*</span></label>
                                <input type="email" value="<?=$user->email?>" name="email" class="form-control">
                                <?= ErrMgr::bind('email') ?>
                            </div>
                            <div class="top-margin">
                                <label>Nif <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->nif?>" name="nif" class="form-control">
                                <?= ErrMgr::bind('nif') ?>
                            </div>
                            <div class="top-margin">
                                <label>Telefone <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->telefone?>" name="telefone" class="form-control">
                                <?= ErrMgr::bind('telefone') ?>
                            </div>

                            <div class="top-margin">
                                <label>Morada <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->morada?>" name="morada" class="form-control">
                                <?= ErrMgr::bind('morada') ?>
                            </div>

                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Guardar</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div
    </article>
    <!-- /Article -->

</div>
</div>
<!-- /container -->

<?php Layout::includeLayout('footer') ?>

