<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('passageiroheader') ?>
<?php $passagens = Data::get('passagens') ?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('passageiro/index')?>">Home</a></li>
        <li class="active">Bilhetes</li>
    </ol>

<!--    <h2 class="text-left top-space">Lista de bilhetes do passageiro --><?//=$passagens->utilizador->nomecompleto?><!--</h2>-->
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>Preço</h3></th><th><h3>Data Compra </h3></th><th><h3>Checkin</h3><th><h3>Ações de Gestão</h3></th></thead>
                <tbody>
                <?php foreach ($passagens as $passagem) { ?>
                    <tr>
                        <td><?=$passagem->precofinal?></td>
                        <td><?=$passagem->datahoracompra?></td>
                        <td><?=$passagem->checkin?></td>
                        <td>
<!--                            <a href="--><?//=Url::toRoute('plane/show', $plane->id)?><!--" class="btn btn-info" role="button">Ver detalhes</a>-->
<!--                            <a href="--><?//=Url::toRoute('plane/edit', $plane->id)?><!--" class="btn btn-warning" role="button">Baixar PDF do Bilhete</a>-->
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
