<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('passageiroheader') ?>
<?php $tickets = Data::get('$tickets'); ?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('passageiro/index')?>">Home</a></li>
        <li class="active">Bilhetes</li>
    </ol>

    <h2 class="text-left top-space">Lista de bilhetes do passageiro</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>nome</h3></th><th><h3>Preço</h3></th><th><h3>Data Compra </h3></th><th><h3>Checkin</h3><th><h3>Ações de Gestão</h3></th></thead>
                <tbody>
                <?php foreach ($tickets as $ticket) { ?>
                    <tr>
                        <td><?=$ticket->utilizador->nomecompleto?></td>
                        <td><?=$ticket->precofinal?></td>
                        <td><?=$ticket->datahoracompra?></td>
                        <td><?=$ticket->checkin?></td>
                        <td>
<!--                            <a href="--><?//=Url::toRoute('passageiro/historicodetalhes', $ticket->id)?><!--" class="btn btn-info" role="button">Ver detalhes</a>-->
                            <a href="<?=Url::toRoute('passageiro/historicopdf', $ticket->id)?>" class="btn btn-warning" role="button">Baixar PDF do Bilhete</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
