<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('passageiroheader'); ?>

<!-- Header -->
<header id="head">
    <div class="container">
        <div class="row">
            <h1 class="lead"><b>Flight Travel Air</b><br>Adquira já a sua passagem!<br></h1>
            <p><br>Para isso pesquise a sua origem e destino e as respetivas datas!<br><br><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('search/index')?>">Pesquise Aqui!</a></p>
        </div>
        <div class="row">
            <br>
            <br>
            <br>
        </div>
    </div>
</header>
<!-- /Header -->

<?php Layout::includeLayout('footer')?>
