<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('passageiroheader') ?>
<?php $user = Data::get('user') ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Dados pessoais <?=$user->username?></h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>

                        <form method="post" action="<?=Url::toRoute('passageiro/index')?>">
                            <div class="top-margin">
                                <label>Nome<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?php echo $user->nomecompleto?>" name="descricao" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Função<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$user->role?>" name="role" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Morada<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$user->morada?>" name="morada" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Email<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$user->email?>" name="email" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>NIF<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$user->nif?>" name="nif" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Telefone<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$user->telefone?>" name="telefone" class="form-control">
                            </div>
                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Voltar</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

