<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/**
 * CRUD Resource Controller for ActiveRecord Model Flight
 *
 * Code generated by WebLogicMVC Code Builder
 *
 * Date: 2021-05-24
 *
 * WL Code Builder developed by Sílvio Priem Mendes
 * *
 */

class FlightController extends BaseController implements ResourceControllerInterface
{
    /**
     * Returns index view with all records
     */
    public function index()
    {
        $flight = Flight::all();
        return View::make('flight.index', ['flight' => $flight]);
    }

    public function indexoperadorcheckin()
    {
        $flight = Flight::all();
        return View::make('flight.indexoperadorcheckin', ['flight' => $flight]);
    }


    /**
     * Returns a view with a form to create a new record
     */
    public function create()
    {
        $aeroport = Aeroport::all();

        $id = [];

        foreach ($aeroport as $a)
        {
            $id = [$a->id];
        }
        var_dump($id);


        return View::make('flight.create');
    }


    /**
     * Receives new record data through POST method and stores it in the DB table
     */
    public function store()
    {
        //create new resource (activerecord/model) instance with data from POST
        //your form name fields must match the ones of the table fields
        $flight = new Flight(Post::getAll());


        if($flight->is_valid()){
            $flight->save();
            Redirect::toRoute('flight/index');
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('flight/create', ['flight' => $flight]);
        }
    }


    /**
     * return a detailed view with record where PK = $id
     */
    public function show($id)
    {
        $flight = Flight::find([$id]);

        if (is_null($flight)) {
            //TODO redirect to standard error page
        } else {
            return View::make('flight.show', ['flight' => $flight]);
        }
    }


    /**
     * return a editable form view with record where PK = $id
     */
    public function edit($id)
    {
        $flight = Flight::find([$id]);

        if (is_null($flight)) {
            //TODO redirect to standard error page
        } else {
            return View::make('flight.edit', ['flight' => $flight]);
        }
    }


    /**
     * Receives record data through POST method and updates it in the DB table
     */
    public function update($id)
    {
        //find resource (activerecord/model) instance where PK = $id
        //your form name fields must match the ones of the table fields
        $flight = Flight::find([$id]);
        $flight->update_attributes(Post::getAll());

        if($flight->is_valid()){
            $flight->save();
            Redirect::toRoute('flight/index');
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('flight/edit', ['flight' => $flight]);
        }
    }


    /**
     * deletes the record where PK = $id
     */
    public function destroy($id)
    {
        $flight = flight::find([$id]);
        $flight->delete();
        Redirect::toRoute('flight/index');
    }

}