<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/**
 * CRUD Resource Controller for ActiveRecord Model Scale
 *
 * Code generated by WebLogicMVC Code Builder
 *
 * Date: 2021-05-24
 *
 * WL Code Builder developed by Sílvio Priem Mendes
 * *
 */

class ScaleController extends BaseController
{
    /**
     * Returns index view with all records
     */
    public function index($idvoo)
    {
        $flights = Flight::find([$idvoo]);
        $planescales = Planescale::all();

        return View::make('scale.index', ['flights' => $flights, 'planescales' => $planescales]);
    }


    /**
     * Returns a view with a form to create a new record
     */
    public function create($idvoo)
    {
        //print_r($idvoo);
        $aeroports = Aeroport::all();

        return View::make('scale.create', ['aeroports' => $aeroports, 'idvoo' => $idvoo]);

    }


    /**
     * Receives new record data through POST method and stores it in the DB table
     */
    public function store($idvoo)
    {
        //create new resource (activerecord/model) instance with data from POST
        //your form name fields must match the ones of the table fields
        $scale = new Scale(Post::getAll());

        if($scale->is_valid()){
            $scale->save();
            //Redirect::toRoute('scale/index');
            $this->index($idvoo);
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('scale/create', ['scale' => $scale, 'idvoo' => $scale->idvoo]);
        }
    }


    /**
     * return a detailed view with record where PK = $id
     */
    public function show($id)
    {
        $scale = Scale::find([$id]);

        if (is_null($scale)) {
            //TODO redirect to standard error page
        } else {
            return View::make('scale.show', ['scale' => $scale]);
        }
    }


    /**
     * return a editable form view with record where PK = $id
     */
    public function edit($id)
    {
        $scale = Scale::find([$id]);
        $aeroports = Aeroport::all();

        if (is_null($scale)) {
            //TODO redirect to standard error page
        } else {
            return View::make('scale.edit', ['scale' => $scale, 'aeroports' => $aeroports]);
        }
    }


    /**
     * Receives record data through POST method and updates it in the DB table
     */
    public function update($id)
    {
        //find resource (activerecord/model) instance where PK = $id
        //your form name fields must match the ones of the table fields
        $scale = Scale::find([$id]);
        $scale->update_attributes(Post::getAll());

        if($scale->is_valid()){
            $scale->save();
            //Redirect::toRoute('scale/index');
            $this->index($scale->idvoo);
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('scale/edit', ['scale' => $scale]);
        }
    }


    /**
     * deletes the record where PK = $id
     */
    public function destroy($id)
    {
        $scale = scale::find([$id]);
        $scale->delete();
        Redirect::toRoute('flight/index');
    }
}