<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader');
$scale = Data::get('scale');
$aeroports = Data::get('aeroports');
$idvoo = Data::get('idvoo');
ErrMgr::attach($scale) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Alterar informações da Escala  <?=$scale->aeroportoorigem->nome?> - <?=$scale->aeroportodestino->nome?></h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('scale/update', $scale->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="datahoraorigem">Data e Hora de Origem:</label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$scale->datahoraorigem?>" class="form-control" required name="datahoraorigem" placeholder="Introduza a data e hora de origem da escala">
                                <?= ErrMgr::bind('datahoraorigem') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="datahoradestino">Data e Hora de Destino:</label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$scale->datahoradestino?>" class="form-control" required name="datahoradestino" placeholder="Introduza a data e hora de destino da escala">
                                <?= ErrMgr::bind('datahoradestino') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="distancia">Distância:</label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$scale->distancia?>" class="form-control" name="distancia" placeholder="Introduza a distância da escala">
                                <?= ErrMgr::bind('distancia') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="idaeroportoorigem">Aeroporto de Origem:</label>
                            <div class="col-sm-6">
                            <select name="idaeroportoorigem" class="form-control" value="<?=$scale->idaeroportoorigem?>">
                                <?php foreach ($aeroports as $aeroport){ ?>
                                    <option value="<?=$aeroport->id?>"><?=$aeroport->nome?></option>
                                <?php } ?>
                            </select>
                            </div>
                            <?= ErrMgr::bind('idaeroportoorigem') ?>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="idaeroportodestino">Aeroporto de Destino<span class="text-danger">*</span>:</label>
                            <div class="col-sm-6">
                            <select name="idaeroportodestino" class="form-control" value="<?=$scale->idaeroportodestino?>">
                                <?php foreach ($aeroports as $aeroport){ ?>
                                    <option value="<?=$aeroport->id?>"><?=$aeroport->nome?></option>
                                <?php } ?>
                            </select>
                            </div>
                            <?= ErrMgr::bind('idaeroportodestino') ?>
                        </div>
                        <div>
                            <input type="hidden" value="<?=$scale->idvoo?>" name="idvoo" class="form-control">
                        </div>
                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>



        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
