<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader');
$flights = Data::get('flights');
$scales = Data::get('scales');
$planescales = Data::get('planescales');
?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('gestorvoo/index')?>">Home</a></li>
        <li><a href="<?=Url::toRoute('flight/index')?>">Voos</a></li>
        <li class="active">Escalas</li>
    </ol>

    <h2 class="text-left top-space">Escalas do Voo nº <?=$flights->id?>, <?= $flights->origem?> - <?= $flights->destino?></h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h4>Data e Hora de Origem</h4></th><th><h4>Data e Hora de Destino</h4><th><h4>Distância</h4></th><th><h4>Aeroporto Origem</h4></th><th><h4>Aeroporto Destino</h4></th><th><h4>Nº Passageiros</h4></th><th><h4>Ações de Gestão</h4></th></thead>
                <tbody>
                <?php foreach ($flights->scales as $scale) {
                        foreach ($planescales as $planescale) {
                            if($planescale->idescala == $scale->id){
                                $nrpassageiros = $planescale->nrpassageiros;
                            }
                        } ?>
                    <tr>
                        <td><?=$scale->datahoraorigem->format('Y-m-d H:i:s')?></td>
                        <td><?=$scale->datahoradestino->format('Y-m-d H:i:s')?></td>
                        <td><?=$scale->distancia?> km</td>
                        <td><?=$scale->aeroportoorigem->nome?></td>
                        <td><?=$scale->aeroportodestino->nome?></td>
                        <td><?=$nrpassageiros?></td>
                        <td>
                            <?php
                            $teste = false;
                            foreach ($planescales as $planescale) {
                                if( $planescale->idescala == $scale->id){
                                    $teste = true;
                                }
                             } if($teste == false){ ?>
                            <a href="<?=Url::toRoute('planescale/create', $scale->id)?>" class="btn btn-info" role="button">Selecionar Avião</a>
                            <?php } ?>
                            <a href="<?=Url::toRoute('scale/edit', $scale->id)?>" class="btn btn-warning" role="button">Editar</a>
                            <a href="<?=Url::toRoute('scale/destroy', $scale->id)?>" class="btn btn-danger" role="button">Eliminar</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>
        <div class="col-sm-6">
            <h3>Registar uma nova Escala</h3>
            <p>
                <a href="<?=Url::toRoute('scale/create', $flights->id)?>" class="btn btn-info" role="button">Registar</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
