<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader') ?>
<?php $scale = Data::get('scale')?>
<?php ErrMgr::attach($scale) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Registar Nova Escala</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('scale/store')?>">
                            <div class="top-margin">
                                <label>Data/Hora de Origem<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$scale->datahoraorigem?>" name="datahoraorigem" class="form-control" placeholder="Introduza o seu nome completo">
                                <?= ErrMgr::bind('datahoraorigem') ?>
                            </div>
                            <div class="top-margin">
                                <label>Data/Hora de Destino<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$scale->datahoradestino?>" name="datahoradestino" class="form-control" placeholder="Introduza o seu nome completo">
                                <?= ErrMgr::bind('datahoradestino') ?>
                            </div>
                            <div>
                                <label>Distância<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$scale->distancia?>" name="distancia" class="form-control" placeholder="Introduza a distância da escala">
                                <?= ErrMgr::bind('distancia') ?>
                            </div>
                            <div class="top-margin">
                                <label>Aeroporto de Origem<span class="text-danger">*</span></label>
                                <select name="idaeroportoorigem" class="form-control" value="<?=$scale->idaeroportoorigem?>">
                                    <option value="<?=Aeroport::find()->where(['id' => $scale->idaeroportoorigem]) ?>">teste</option>
                                </select>
                                <?= ErrMgr::bind('idaeroportoorigem') ?>
                            </div>
                            <div class="top-margin">
                                <label>Aeroporto de Destino<span class="text-danger">*</span></label>
                                <select name="idaeroportodestino" class="form-control" value="<?=$scale->idaeroportodestino?>">
                                    <option value="<?=Aeroport::find()->where(['id' => $scale->idaeroportodestino]) ?>">teste</option>
                                </select>
                                <?= ErrMgr::bind('idaeroportodestino') ?>
                            </div>
                            <div class="top-margin">
                                <label>Voo associado<span class="text-danger">*</span></label>
                                <select name="idvoo" class="form-control" value="<?=$scale->idvoo?>">
                                    <option value="<?=Flight::find()->where(['id' => $scale->idvoo]) ?>">teste</option>
                                </select>
                                <?= ErrMgr::bind('idvoo') ?>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Criar</button>
                            </div>
                    </div>
                    </form>
                </div>
                <form method="post" action="<?=URL::toRoute('scale/index')?>">
                    <button class="btn btn-danger" type="submit">Cancelar</button>
                </form>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
