<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('adminheader') ?>
<?php $scale = Data::get('scale')?>
<?php ErrMgr::attach($scale) ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Alterar informações da escala <?=$scale->id?></h1>
            </header>


            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <form class="form-horizontal" method="post" action="<?=Url::toRoute('scale/update', $scale->id)?>">

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="datahoraorigem">Data e Hora de Origem<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$scale->datahoraorigem?>" class="form-control" required name="datahoraorigem" placeholder="Introuza o seu nome completo">
                                <?= ErrMgr::bind('datahoraorigem') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="datahoradestino">Data e Hora de Destino<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" value="<?=$scale->datahoradestino?>" class="form-control" required name="datahoradestino" placeholder="Introuza o seu nome completo">
                                <?= ErrMgr::bind('datahoradestino') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="distancia">Distância<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" required value="<?=$scale->distancia?>" class="form-control" name="distancia" placeholder="Introduza a distância da escala">
                                <?= ErrMgr::bind('distancia') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="idaeroportoorigem">Aeroporto de Origem<span class="text-danger">*</span></label>
                            <select name="idaeroportoorigem" class="form-control" value="<?=$scale->idaeroportoorigem?>">
                                <option value="<?=Aeroport::find()->where(['id' => $scale->idaeroportoorigem]) ?>">teste</option>
                            </select>
                            <?= ErrMgr::bind('idaeroportoorigem') ?>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="idaeroportodestino">Aeroporto de Destino<span class="text-danger">*</span></label>
                            <select name="idaeroportodestino" class="form-control" value="<?=$scale->idaeroportodestino?>">
                                <option value="<?=Aeroport::find()->where(['id' => $scale->idaeroportodestino]) ?>">teste</option>
                            </select>
                            <?= ErrMgr::bind('idaeroportodestino') ?>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="idvoo">Voo associado<span class="text-danger">*</span></label>
                            <select name="idvoo" class="form-control" value="<?=$scale->idvoo?>">
                                <option value="<?=Flight::find()->where(['id' => $scale->idvoo]) ?>">teste</option>
                            </select>
                            <?= ErrMgr::bind('idvoo') ?>
                        </div>
                        <hr>

                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>



        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
