<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('gestorVooheader') ?>
<?php $scales = Data::get('scale') ?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('admin/index')?>">Home</a></li>
        <li class="active">Escalas</li>
    </ol>

    <h2 class="text-left top-space">Lista de Escalas</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>Data e Hora de Origem</h3></th><th><h3>Data e Hora de Destino</h3><th><h3>Distância</h3></th><th><h3>Aeroporto de Origem</h3></th><th><h3>Aeroporto de Destino</h3></th><th><h3>Voo Associado</h3></th><th><h3>Ações de Gestão</h3></th></thead>
                <tbody>
                <?php foreach ($scales as $scale) { ?>
                    <tr>
                        <td><?=$scale->datahoraorigem?></td>
                        <td><?=$scale->datahoradestino?></td>
                        <td><?=$scale->distancia?></td>
                        <td><?=$scale->idaeroportoorigem?></td>
                        <td><?=$scale->idaeroportodestino?></td>
                        <td><?=$scale->idvoo?></td>
                        <td>
                            <a href="<?=Url::toRoute('scale/show', $scale->id)?>" class="btn btn-info" role="button">Ver detalhes</a>
                            <a href="<?=Url::toRoute('scale/edit', $scale->id)?>" class="btn btn-warning" role="button">Editar</a>
                            <a href="<?=Url::toRoute('scale/destroy', $scale->id)?>" class="btn btn-danger" role="button">Eliminar</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

        </div>
        <div class="col-sm-6">
            <h3>Registar Nova Escala</h3>
            <p>
                <a href="<?=Url::toRoute('scale/create')?>" class="btn btn-info" role="button">Novo</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
