<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('gestorVooheader') ?>
<?php $scale = Data::get('scale') ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Informações da escala <?=$scale->id?></h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>

                        <form method="post" action="<?=Url::toRoute('scale/index')?>">
                            <div class="top-margin">
                                <label>Data e Hora de origem<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?php echo $scale->datahoraorigem?>" name="datahoraorigem" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Data e Hora de destino<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$scale->datahoradestino?>" name="datahoradestino" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Distancia<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$scale->distancia?>" name="distancia" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Aeroporto de origem<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$scale->idaeroportoorigem?>" name="idaeroportoorigem" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Aeroporto de destino<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$scale->idaeroportodestino?>" name="idaeroportodestino" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Voo associado<span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$scale->idvoo?>" name="idvoo" class="form-control">
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Voltar</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
