<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('operadorCheckinheader');
$users = Data::get('users');
$tickets = Data::get('tickets');
ErrMgr::attach($users) ?>


    <div class="container">

        <ol class="breadcrumb">
            <li><a href="<?=Url::toRoute('operadorcheckin/index')?>">Home</a></li>
            <li class="active">Lista de Passageiros para realizar checkin</li>
        </ol>

        <h2 class="text-left top-space">Lista de Passageiros</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>ID Utilizador</h3></th><th><h3>ID Bilhete</h3></th><th><h3>Realizar Checkin / Detalhes de Voo</h3></th></thead>
                    <tbody>
                    <?php foreach ($tickets as $ticket) { ?>

                        <tr>
                            <td><?=$ticket->idutilizador?></td>
                            <td><?=$ticket->id?></td>
                            <td>
                                <a href="<?=Url::toRoute('ticket/edit', $ticket->id)?>" class="btn btn-warning" role="button">Checkin</a>
                                <a href="<?=Url::toRoute('ticket/show', $ticket->id)?>" class="btn btn-warning" role="button">Detalhes Voo</a>
                            </td>
                        </tr>

                    <?php } ?>
                    </tbody>
                </table>
            </div>

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>