<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Debug;

Layout::includeLayout('operadorCheckinheader') ?>
<?php $tickets = Data::get('tickets') ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Informações do voo do passageiro <?=$tickets->utilizador->nomecompleto?></h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>

                        <form method="post" action="<?=Url::toRoute('operadorcheckin/checkin')?>">
                            <h3 class="page-title">Detalhes do Voo de Ida</h3>
                            <div class="top-margin">
                                <label>Preco Final</label>
                                <input readonly="true" type="text" value="<?php echo $tickets->precofinal?>" name="precofinal" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Origem</label>
                                <input readonly="true" type="text" value="<?=$tickets->vooida->origem?>" name="origem" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Destino</label>
                                <input readonly="true" type="text" value="<?=$tickets->vooida->destino?>" name="destino" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Data de Origem</label>
                                <input readonly="true" type="text" value="<?=$tickets->vooida->dataorigem?>" name="dataorigem" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Data de Destino</label>
                                <input readonly="true" type="text" value="<?=$tickets->vooida->datadestino?>" name="datadestino" class="form-control">
                            </div>

                            <label>___________________________________________________________________</label>

                            <h3 class="page-title">Detalhes do Voo de Volta</h3>
                            <div class="top-margin">
                                <label>Preco Final</label>
                                <input readonly="true" type="text" value="<?php echo $tickets->precofinal?>" name="precofinal" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Origem</label>
                                <input readonly="true" type="text" value="<?=$tickets->voovolta->origem?>" name="origem" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Destino</label>
                                <input readonly="true" type="text" value="<?=$tickets->voovolta->destino?>" name="destino" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Data de Origem</label>
                                <input readonly="true" type="text" value="<?=$tickets->voovolta->dataorigem?>" name="dataorigem" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Data de Destino</label>
                                <input readonly="true" type="text" value="<?=$tickets->voovolta->datadestino?>" name="datadestino" class="form-control">
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Voltar</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

