<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('operadorCheckinheader'); ?>

<!-- Header -->
<header id="head">
    <div class="container">
        <div class="row">
            <h1 class="lead"><b>Flight Travel Air</b><br>Área de operador de checkin</h1>
            <p class="tagline">Gestão de checkin de um passageiro e detalhes de voos.<br><br><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('operadorcheckin/checkin')?>">Realizar Checkin / Detalhes Voo</a></p>
        </div>
        <div class="row">
            <br>
            <br>
            <br>
        </div>
    </div>
</header>
<!-- /Header -->


<?php Layout::includeLayout('footer')?>
