<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('home/index')?>">Home</a></li>
        <li class="active">Login de Utilizadores</li>
    </ol>

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Login / Registo</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="thin text-center">Faça login na sua conta</h3>
                        <p class="text-center text-muted"><a href="<?=URL::toRoute('login/getregisto')?>">Não tem uma conta? Registe-se aqui!</a></p>
                        <hr>

                        <form action="<?=URL::toRoute('login/login')?>" method="post">
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="username">
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" class="form-control" name="password">
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-lg-8">
                                </div>
                                <div class="col-lg-4 text-center">
                                    <button class="btn btn-action" type="submit">Login</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </article>
        <!-- /Article -->

    </div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
