<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $user = Data::get('user')?>
<?php ErrMgr::attach($user) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Registar Novo Cliente</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('login/registo')?>">
                            <div class="top-margin">
                                <label>Nome Completo <span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$user->nomecompleto?>" name="nomecompleto" class="form-control" placeholder="Insira o seu nome completo">
                                <?= ErrMgr::bind('nomecompleto') ?>
                            </div>
                            <div class="top-margin">
                                <label>Morada <span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$user->morada?>" name="morada" class="form-control" placeholder="Insira a sua morada">
                                <?= ErrMgr::bind('morada') ?>
                            </div>
                            <div>
                                <label>Email<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$user->email?>" name="email" class="form-control" placeholder="Insira o seu email">
                                <?= ErrMgr::bind('email') ?>
                            </div>
                            <div>
                                <label>NIF<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$user->nif?>" name="nif" class="form-control" placeholder="Insira o seu nif">
                                <?= ErrMgr::bind('nif') ?>
                            </div>
                            <div>
                                <label>Telefone<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$user->telefone?>" name="telefone" class="form-control" placeholder="Insira o seu número de telefone">
                                <?= ErrMgr::bind('telefone') ?>
                            </div>
                            <div>
                                <label>Username<span class="text-danger">*</span></label>
                                <input type="text" autocomplete="off" value="<?=$user->username?>" name="username" class="form-control" placeholder="Insira o seu username">
                                <?= ErrMgr::bind('username') ?>
                            </div>
                            <div>
                                <label>Palavra chave<span class="text-danger">*</span></label>
                                <input type="password" autocomplete="off" value="<?=$user->password?>" name="password" class="form-control" placeholder="Insira a sua password">
                                <?= ErrMgr::bind('password') ?>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">New</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>
