<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('passageiroheader');
$flights = Data::get('flights');
$user = Data::get('user');
ErrMgr::attach($user);
?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Voo nº <?= $flights->id?>, <?= $flights->origem?> - <?= $flights->destino?></h1>
                <h3>Preço: <?= $flights->precovoo?>€</h3>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('ticket/store')?>">
                            <div class="top-margin">
                                <label>Nome Completo:</label>
                                <input type="text" value="<?=$user->nomecompleto?>" class="form-control">
                                <?= ErrMgr::bind('nomecompleto') ?>
                            </div>
                            <div class="top-margin">
                                <label>Email:</label>
                                <input type="email" value="<?=$user->email?>" class="form-control">
                                <?= ErrMgr::bind('email') ?>
                            </div>
                            <div class="top-margin">
                                <label>Nif:</label>
                                <input type="text" value="<?=$user->nif?>" class="form-control">
                                <?= ErrMgr::bind('nif') ?>
                            </div>
                            <div class="top-margin">
                                <label>Telefone:</label>
                                <input type="text" value="<?=$user->telefone?>" class="form-control">
                                <?= ErrMgr::bind('telefone') ?>
                            </div>

                            <div class="top-margin">
                                <label>Morada:</label>
                                <input type="text" value="<?=$user->morada?>" class="form-control">
                                <?= ErrMgr::bind('morada') ?>
                            </div>

                            <div class="top-margin">
                                <label>Número do cartão de crédito:</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Validade Mês / Validade Ano</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>CVC:</label>
                                <input type="text" class="form-control">
                            </div>


                            <div>
                                <input type="hidden" value="<?=$flights->precovoo + 20?>" name="precofinal" class="form-control">
                            </div>

                            <div>
                                <input type="hidden" value= name="datahoracompra" class="form-control">
                            </div>

                            <div>
                                <input type="hidden" value= name="checkin" class="form-control">
                            </div>

                            <div>
                                <input type="hidden" value="<?=$flights->id?>" name="idvooida" class="form-control">
                            </div>

                            <div>
                                <input type="hidden" value="<?=$flights->id?>" name="idvoovolta" class="form-control">
                            </div>

                            <div>
                                <input type="hidden" value="<?=$user->id?>" name="idutilizador" class="form-control">
                            </div>

                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Next</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div
        </article>
        <!-- /Article -->

    </div>
</div>
<!-- /container -->

<?php Layout::includeLayout('footer') ?>

