<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('passageiroheader');
$flights = Data::get('flights');
?>

<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Detalhes dos Voos</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('search/comprarticket', $flights->id)?>">
                            <div class="top-margin">
                                <label>Origem</label>
                                <input readonly="true" type="text" value="<?=$flights->origem?>" name="origem" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Destino</label>
                                <input readonly="true" type="text" value="<?=$flights->destino?>" name="destino" class="form-control">
                            </div>


                            <div class="top-margin">
                                <label>Data de Origem</label>
                                <input readonly="true" type="text" value="<?=$flights->dataorigem->format('Y-m-d')?>" name="dataorigem" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Data de Destino</label>
                                <input readonly="true" type="text" value="<?=$flights->datadestino->format('Y-m-d')?>" name="datadestino" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Preço do Voo</label>
                                <input  readonly="true" type="text" value="<?=$flights->precovoo?>" name="precovoo" class="form-control">
                            </div>

                            <h2 class="page-title">Escalas do Voo</h2>

                            <?php foreach ($flights->scales as $scale) {?>

                                <label>__________________________________________________________________</label>
                                <div class="top-margin">
                                    <label>Origem da Escala nº<?=$scale->id ?></label>

                                    <input  readonly="true" type="text" value="<?=$scale->aeroportoorigem->nome ?>" name="aeroportoorigem" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Data e Hora de Origem da Escala nº<?=$scale->id ?></label>

                                    <input  readonly="true" type="text" value="<?=$scale->datahoraorigem->format('Y-m-d H:i:s') ?>" name="datahoraorigem" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Destino da Escala nº<?=$scale->id ?></label>
                                    <input  readonly="true" type="text" value="<?=$scale->aeroportodestino->nome ?>" name="aeroportodestino" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Data e Hora de Destino da Escala nº<?=$scale->id ?></label>

                                    <input  readonly="true" type="text" value="<?=$scale->datahoradestino->format('Y-m-d H:i:s') ?>" name="datahoradestino" class="form-control">
                                </div>

                            <?php } ?>
                            <hr>
                            <div class="col-lg-4 text-left">
                                <a href="<?=Url::toRoute('search/index')?>" class="btn btn-danger" role="button">Voltar</a>
                            </div>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Comprar passagem</button>
                            </div>


                    </div>
                    </form>
                </div>
            </div>
    </div>

    </article>
    <!-- /Article -->
</div>
</div>	<!-- /container -->
<?php Layout::includeLayout('footer');?>


