<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('passageiroheader');
?>

<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Pesquisa de Voos</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('search/show')?>">
                            <div class="top-margin">
                                <label>Origem<span class="text-danger">*</span></label>
                                <input type="text" value=""  name="origem" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Destino<span class="text-danger">*</span></label>
                                <input type="text" value="" name="destino" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Data de origem </label>
                                <input type="date"  value="" name="dataorigem" class="form-control">
                            </div class="top-margin">

                            <div class="top-margin">
                                <label>Data de destino </label>
                                <input type="date"  value="" name="datadestino" class="form-control">
                            </div>

                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Pesquisar</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>
    </div>

    </article>
    <!-- /Article -->
</div>
</div>	<!-- /container -->
<?php Layout::includeLayout('footer');?>

