<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('passageiroheader');
$flights = Data::get('flights');
$flightsvolta = Data::get('flightsvolta');
?>

<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?=Url::toRoute('passageiro/index')?>">Home</a></li>
        <li class="active">Voos</li>
    </ol>

    <h2 class="text-left top-space">Voo de ida</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>Origem</h3></th><th><h3>Data de Origem</h3></th><th><h3>Destino</h3></th><th><h3>Data de Destino</h3></th><th><h3>Ações de Gestão</h3></th></thead>
                <tbody>
                <?php foreach ($flights as $flight) { ?>
                    <tr>
                        <td><?=$flight->origem?></td>
                        <td><?=$flight->dataorigem?></td>
                        <td><?=$flight->destino?></td>
                        <td><?=$flight->datadestino?></td>

                        <td>
                            <a href="<?=Url::toRoute('search/detalhes', $flight->id)?>" class="btn btn-info" role="button">Detalhes</a>
                            <a href="<?=Url::toRoute('search/comprarticket', $flight->id)?>" class="btn btn-warning" role="button">Comprar passagem</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div> <!-- /row -->

    <h2 class="text-left top-space">Voo de Volta</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-1-12">
            <table class="table table-striped"><thead><th><h3>Origem</h3></th><th><h3>Data de Origem</h3></th><th><h3>Destino</h3></th><th><h3>Data de Destino</h3></th><th><h3>Ações de Gestão</h3></th></thead>
                <tbody>
                <?php foreach ($flightsvolta as $flightvolta) { ?>
                    <tr>
                        <td><?=$flightvolta->destino?></td>
                        <td><?=$flightvolta->dataorigem?></td>
                        <td><?=$flightvolta->origem?></td>
                        <td><?=$flightvolta->datadestino?></td>

                        <td>
                            <a href="<?=Url::toRoute('search/detalhes', $flightvolta->id)?>" class="btn btn-info" role="button">Detalhes</a>
                            <a href="<?=Url::toRoute('search/comprarticket', $flightvolta->id)?>" class="btn btn-warning" role="button">Comprar passagem</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>




